services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rails:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      RACK_ENV: ${RACK_ENV}
      RAILS_ENV: ${RAILS_ENV}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      RAILS_MAX_THREADS: ${RAILS_MAX_THREADS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      USER_ID: ${USER_ID}
      GROUP_ID: ${GROUP_ID}
    volumes:
      - ./backend:/rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - rails
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_BACKEND_HOST=${BACKEND_HOST}

volumes:
  pg_data:
    external: true